### ISSUE TITLE
Uncommited Repo

### ISSUE THREAD

**Issue by ibratabian17** [NusantaraProject-ROM/android_manifest#6]
Sync failed because something went wrong with the repo

`
repo has been initialized in /home/cirrus/roms/NusantaraProject-ROM
Cloning into '.repo/local_manifests'...
info: A new version of repo is available
warning: 'refs/heads/v2.16.8-40-g0f6f16e' is not signed; falling back to signed release 'v2.16.8'
warning: Skipped upgrade to unverified version
error: vendor/xiaomi/juice: Cannot remove project: uncommitted changes are present.

vendor/nxp/opensource/pn5xx/halimpl: Shared project android_vendor_nxp_opensource_halimpl found, disabling pruning.

vendor/nxp/opensource/sn100x/halimpl: Shared project android_vendor_nxp_opensource_halimpl found, disabling pruning.

device/qcom/sepolicy: Shared project android_device_qcom_sepolicy found, disabling pruning.

device/qcom/sepolicy-legacy: Shared project android_device_qcom_sepolicy found, disabling pruning.

vendor/nxp/opensource/pn5xx/hidlimpl: Shared project android_vendor_nxp_opensource_hidlimpl found, disabling pruning.

vendor/nxp/opensource/sn100x/hidlimpl: Shared project android_vendor_nxp_opensource_hidlimpl found, disabling pruning.

hardware/qcom-caf/msm8952/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/msm8994/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/msm8996/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/msm8998/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/sdm845/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/sm8150/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/sm8250/audio: Shared project android_hardware_qcom_audio found, disabling pruning.

hardware/qcom-caf/msm8952/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/msm8994/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/msm8996/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/msm8998/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/sdm845/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/sm8150/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/sm8250/display: Shared project android_hardware_qcom_display found, disabling pruning.

hardware/qcom-caf/msm8952/media: Shared project android_hardware_qcom_media found, disabling pruning.

hardware/qcom-caf/msm8994/media: Shared project android_hardware_qcom_media found, disabling pruning.

hardware/qcom-caf/msm8996/media: Shared project android_hardware_qcom_media found, disabling pruning.

hardware/qcom-caf/msm8998/media: Shared project android_hardware_qcom_media found, disabling pruning.

hardware/qcom-caf/sdm845/media: Shared project android_hardware_qcom_media found, disabling pruning.

hardware/qcom-caf/sm8150/media: Shared project android_hardware_qcom_media found, disabling pruning.

hardware/qcom-caf/sm8250/media: Shared project android_hardware_qcom_media found, disabling pruning.
repo: Updating release signing keys to keyset ver 2.3

device/lenovo/A6020/: discarding 1 commits
hardware/qcom-caf/sdm845/display/: discarding 1 commits
error: Unable to fully sync the tree.
error: Updating local project lists failed.
Try re-running with "-j1 --fail-fast" to exit at the first error.
`

**Comment by Orel6505** [comment]
Your Error:
warning: 'refs/heads/v2.16.8-40-g0f6f16e' is not signed; falling back to signed release 'v2.16.8'
warning: Skipped upgrade to unverified version
error: vendor/xiaomi/juice: Cannot remove project: uncommitted changes are present.

**Comment by goodmeow** [comment]
this has no issue with the source, check your failed repo.
